# Generated by Django 4.0.5 on 2022-09-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40)),
                ('key_pair_name', models.CharField(max_length=40)),
                ('flavor', models.CharField(choices=[('x1.small', 'X1.SMALL'), ('x1.medium', 'X1.MEDIUM'), ('x1.large', 'X1.LARGE')], default='x1.small', max_length=40)),
                ('image', models.CharField(choices=[('centos', 'CENTOS'), ('ubuntu', 'UBUNTU')], default='ubuntu', max_length=40)),
                ('worker', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
